[2024-08-28T12:11:34.358+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-28T12:11:34.409+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hubspot_to_postgres.run_hubspot_script scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2024-08-28T12:11:34.442+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hubspot_to_postgres.run_hubspot_script scheduled__2023-09-30T00:00:00+00:00 [queued]>
[2024-08-28T12:11:34.444+0000] {taskinstance.py:2856} INFO - Starting attempt 2 of 2
[2024-08-28T12:11:34.521+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): run_hubspot_script> on 2023-09-30 00:00:00+00:00
[2024-08-28T12:11:34.529+0000] {standard_task_runner.py:72} INFO - Started process 767 to run task
[2024-08-28T12:11:34.532+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'hubspot_to_postgres', 'run_hubspot_script', 'scheduled__2023-09-30T00:00:00+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/hubspot_to_postgres_dag.py', '--cfg-path', '/tmp/tmpcpbf7qpa']
[2024-08-28T12:11:34.534+0000] {standard_task_runner.py:105} INFO - Job 122: Subtask run_hubspot_script
[2024-08-28T12:11:34.670+0000] {task_command.py:467} INFO - Running <TaskInstance: hubspot_to_postgres.run_hubspot_script scheduled__2023-09-30T00:00:00+00:00 [running]> on host 9e43cf90fc4e
[2024-08-28T12:11:34.938+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='hubspot_to_postgres' AIRFLOW_CTX_TASK_ID='run_hubspot_script' AIRFLOW_CTX_EXECUTION_DATE='2023-09-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-30T00:00:00+00:00'
[2024-08-28T12:11:34.940+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-28T12:11:35.737+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/hubspot_extractor_postgreSQL.py", line 227, in extract_and_load_data
    'contacts': '/crm/v3/objects/contacts?properties=' + ','.join(get_all_contact_properties())
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/hubspot_extractor_postgreSQL.py", line 87, in get_all_contact_properties
    raise Exception(f"Failed to retrieve properties: {response.status_code} {response.reason}")
Exception: Failed to retrieve properties: 401 Unauthorized
[2024-08-28T12:11:35.783+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=hubspot_to_postgres, task_id=run_hubspot_script, run_id=scheduled__2023-09-30T00:00:00+00:00, execution_date=20230930T000000, start_date=20240828T121134, end_date=20240828T121135
[2024-08-28T12:11:35.884+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-28T12:11:35.886+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 122 for task run_hubspot_script (Failed to retrieve properties: 401 Unauthorized; 767)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/hubspot_extractor_postgreSQL.py", line 227, in extract_and_load_data
    'contacts': '/crm/v3/objects/contacts?properties=' + ','.join(get_all_contact_properties())
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/hubspot_extractor_postgreSQL.py", line 87, in get_all_contact_properties
    raise Exception(f"Failed to retrieve properties: {response.status_code} {response.reason}")
Exception: Failed to retrieve properties: 401 Unauthorized
[2024-08-28T12:11:35.914+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-08-28T12:11:35.968+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-28T12:11:35.974+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
